### ISSUE TITLE
Error when adding via HACS

### ISSUE THREAD

**Issue by bastichelaar** [signalkraft/mypyllant-component#1]
Awesome that you made this component! Unfortunately I encountered an error when adding it to Home Assistant:

custom_components.mypyllant

```
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.mypyllant
Source: deps/lib/python3.10/site-packages/myPyllant/models.py:114
Integration: myVAILLANT (documentation, issues)
First occurred: 23:03:40 (2 occurrences)
Last logged: 23:03:40

Unexpected error fetching myVAILLANT data: 1 validation error for Zone humidity field required (type=value_error.missing)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/mypyllant/__init__.py", line 114, in _async_update_data
    data = [
  File "/config/custom_components/mypyllant/__init__.py", line 114, in <listcomp>
    data = [
  File "/config/deps/lib/python3.10/site-packages/myPyllant/api.py", line 199, in get_systems
    system = System(
  File "/config/deps/lib/python3.10/site-packages/myPyllant/models.py", line 114, in __init__
    self.zones = [Zone(system_id=self.id, **z) for z in self._raw_zones]
  File "/config/deps/lib/python3.10/site-packages/myPyllant/models.py", line 114, in <listcomp>
    self.zones = [Zone(system_id=self.id, **z) for z in self._raw_zones]
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Zone
humidity
  field required (type=value_error.missing)

```

Using the component with a VR921. Thanks!

**Comment by signalkraft** [comment]
Thanks for reporting, try out https://github.com/signalkraft/mypyllant-component/releases/tag/v0.0.12 - I made the missing field optional.

This sort of problem will probably pop up a few more times while you're setting up this component, because I had no way of testing which data the myVAILLANT API returns for different installations. Please turn on debug logging for this integration if you encounter another problem and add it to this issue.

**Comment by signalkraft** [comment]
@erikvtv I created a new release that may fix your problem.

This sort of problem will probably pop up a few more times while you're setting up this component, because I had no way of testing which data the myVAILLANT API returns for different installations. Please turn on debug logging for this integration if you encounter another problem and add it to this issue.

**Comment by erikvtv** [comment]
Hi Signalkraft,

thx v0.018 is fixing the problem

**Comment by signalkraft** [comment]
@erikvtv glad to hear that!
