### ISSUE TITLE
Error fetching myVAILLANT data: 503, Error fetching myVAILLANT data: 500, Error fetching myVAILLANT data: 403

### ISSUE THREAD

**Issue by bartmarchand1** [signalkraft/mypyllant-component#151]
### Before submitting a new issue

- [X] I [redownloaded the latest release](https://my.home-assistant.io/redirect/hacs_repository/?owner=signalkraft&repository=mypyllant-component) and restarted Home Assistant
- [X] I've checked [known issues](https://signalkraft.com/mypyllant-component/#known-issues)
- [X] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

### Problem description

Since a started using this integration there are errors in the logs.

### Logs

[new 3.txt](https://github.com/signalkraft/mypyllant-component/files/14771005/new.3.txt)

**Comment by signalkraft** [comment]
500 errors indicate that something went wrong on Vaillant's side. The API can be a bit unstable at times.

**Comment by Brati123** [comment]
Since yesterday night I find this error code:

Logger: custom_components.mypyllant.coordinator
Quelle: helpers/update_coordinator.py:497
Integration: myVAILLANT (Dokumentation, Probleme)
Erstmals aufgetreten: 18. Mai 2026 um 23:43:04 (4 Vorkommnisse)
Zuletzt protokolliert: 06:11:34

Error fetching myVAILLANT data: 503, message='Service Temporarily Unavailable', url='https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/emf/v2/.../currentSystem'
Error fetching myVAILLANT data: 503, message='Service Temporarily Unavailable', url='https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/emf/v2/.../devices/.../buckets?resolution=HOUR&operationMode=DOMESTIC_HOT_WATER&energyType=CONSUMED_ELECTRICAL_ENERGY&startDate=2026-05-19T00:00:00.000%2B02:00&endDate=2026-05-20T00:00:00.000%2B02:00'
Error fetching myVAILLANT data: No systems available for daily data fetch

**Comment by hammy1988** [comment]
@Brati123 should be working again, if you reload the integration.
Look at this issue: https://github.com/signalkraft/mypyllant-component/issues/444

**Comment by Brati123** [comment]
Thank you so much! Yes, it is working again.
