### ISSUE TITLE
Q: Control of circulation pump

### ISSUE THREAD

**Issue by boelle** [signalkraft/mypyllant-component#20]
is it possible to stop the circulation pump ?

no sense in having that going if not producing heat

**Comment by DerGali2020** [comment]
Vaillant added zirculation settings (only time based) in the last update from this month.

**Comment by boelle** [comment]
Oki will look later today



ons. 26. jul. 2023 12.34 skrev DerGali2020 ***@***.***>:

**Comment by boelle** [comment]
Just tried and I use the multimatic integration

I guess they only added it myvaillant. I have not been invited to upgrade
yet so assume I have to wait

ons. 26. jul. 2023 12.34 skrev DerGali2020 ***@***.***>:

**Comment by boelle** [comment]
@DerGali2020 I know that i can create a time table/schedule in the senso app

currently i use this integration: https://community.home-assistant.io/t/vaillant-multimatic-integration/87240

it says it does not work with the senso app but it does, the only thing i miss there are some way to turn the circulation pump on/off...  or as a workaround create a schedule does the same thing

on top of that i dont seem to get a lot of repsonse when i post something there so feel its kind of defunct

i have just asked vaillant in DK when i get an invite to use the myvaillant app instead

at least someone here responded :-)

**Comment by signalkraft** [comment]
Someone with the myvaillant app and a circulation pump in their setup would need to figure out if there are controls for the pump, and if there are then [reverse the API calls](https://github.com/signalkraft/mypyllant#reverse-engineering-api-requests-of-the-myvaillant-app) and post the results here.

**Comment by boelle** [comment]
Agree, sadly vaillant in Germany have not released myvaillant in Denmark yet

but everyone that has a heatpump for house heating would have a circulation pump to move the water arround in the radiators

should we keep this one open just as a reminder of some sort?

**Comment by DerGali2020** [comment]
i think we are talking about 2 diffrent circulation pumps, where one is called heating water pump here in germany. The heating water pump is automatically controlled by the heatpump, which totaly makes sense. It will stop automatically if the heating is off or heatpump is making hot tapwater. If your heating pump is running all year, your heatpump system is not set or cabled correctly. I can only talk for versotherm because i cabled this thing and configured it together with the heating company. Water circulation settings in the myvaillant app is only for hot tapwater, it helps to get instant hot water if you open the tap. 
@signalkraft i will take a look to get an api dump. Since 0.3x all versotherm data is being collected.

**Comment by boelle** [comment]
my unit is an aerotherm VWL 105/5 AS S2

and you are right.... i just noted it now that there is a tap icon

![image](https://github.com/signalkraft/mypyllant-component/assets/3832239/6d6a6502-1dd2-4569-850a-a3a490ccb763)

i feel like a fool for not noting that before :-(

**Comment by signalkraft** [comment]
The circulation pump for hot water should now be programmable with a new custom service, see the notes on https://github.com/signalkraft/mypyllant-component/releases/tag/v0.5.4

**Comment by boelle** [comment]
hehe, now i just have to wait for myvaillant to be released in denmark

and save up more cash to renovate the house, need to dig up the floors under the bathroom and kitchen so i can add the return line

side q.. how do i figure if it makes sense to have a return on hot water? i assume its figuring the cost of X amount of liters of cold water before it becomes hot vs. running the circulation pump.... but is it that simple math or are there more to it?

**Comment by DerGali2020** [comment]
From an energy standpoint it doesn't make sense at all to add a return line + circulation pump. In many homes hot water is stored in a tank where the temperature could be held for days of no water is used. A lot of houses have no or bad isolation of hot water pipes. If you cycle the water around the house . The Water in the tank had to heat up much more often than without circulation. It's like heating up the house via hot water pipes. It gets installed for two reasons:
1. Comfort
Open the tap and you have hot water instantly without waiting the cold water run through. Some people are using automations to trigger the circulation pump, via a light switch or Alexa etc.. If you enter the bathroom or kitchen the circulation pump gets activated and you can start to shower instantly or washing the dishes. Some let them run only for a few minutes a day because their water pipes are isolated and can hold the temperature much longer 
2. Minimizing the risk of bacteria growing
If hot water stands for a long time in a pipe it could help bacteria in the water to grow. It keeps the water flowing. A lot of people says it shouldn't be an issue in a home for one family because hot water is used regularly. On that you could open a discussion how much to heat up the hot water 45 degrees or 55 degrees (which should stop the growing of bacteria) and even heat up the tank water in combination with circulation pump to 65 or 75 degrees once week to remove all bacteria. If you ask 10 ten people about this topic I think you will get 10 different answers :-). There are installations without a hot water tank or a hot water tank only heat up the hot water via a heat exchanger which removes this issue mostly.

With heatpumps a lot of people try to minimize the usage of heating up the water to save up energy and save up starts of the compressor which could help to increase the lifetime of your heatpump.

For example in my home the company set the circulation pump to run the whole day (6-20) which caused 110-120 kWh per month for hot water (at 55 degrees) for one family. After changing it to 3 times a day for 10 minutes it reduced the consumption to 70-80 kWh per month.people who don't use circulation at all and are using lower temperatures have much less consumption.

**Comment by boelle** [comment]
as for saving on cost i have allready set home assistant to get the electricity prices and heat up hot water when its cheapest and turn off heting the hot water when its at 55, that is enough to kill legionella. and one heat up is enough for 3 persons, it normal heats the water in 45 mins or less

as for the house heating i have home assistant pulling the smoke alarm for temperature once an hour and also getting outside temperature from open weather map.... if temp at first floor is above 20.5 it will tell the heatpump to go one degree down... is its below 20 it will go one degree up....

if outside temp is above 12 degree it will allow the heatpump to go all the way down to 5 degree and in effect become inactive, it if go below 12 outside it will go down to 21 degree.... if below 10 outside it will go to 23 degree's.... i might add more minimums as we go to sub zero 

so i think i will skip installing the return line even thou i will still have to dig up the floors to add insulation under them and to lower them.... and yes as you say if the pipe is not insulated well the heat will just go out in the floor

and then again... if showers are planned you could circulate the water in advance... but yeah shower is next to room where the inside part of the heatpump and hot water tank is installed.... think i will skip it

**Comment by signalkraft** [comment]
I'm closing this as fixed for now, for more discussions about circulation setups, feel free to use the discussions tabs in this repo, or [the HA thread](https://community.home-assistant.io/t/myvaillant-integration/542610).
